openapi: 3.0.0
info:
  title: "Shapes API"
  description: "Provides an API for creating shapes and calculating their square"
  version: 1.0.0
paths:
  /figure:
    post:
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Circle'
                - $ref: '#/components/schemas/Triangle'
                - $ref: '#/components/schemas/Rectangle'
              discriminator:
                propertyName: shapeType
      responses:
        "201":
          description: "Created"
        "400":
          description: "Bad request"
  /figure/{id}:
    get:
      summary: Gets a figure by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '404':
          description: Figure not found
        '200':
          description: A figure info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SquareResponse'
components:
  schemas:
    Figure:
      type: object
      properties:
        shapeType:
          type: string
          enum:
          - "circle"
          - "triangle"
          - "rectangle"
    Circle:
      allOf:
        - $ref: '#/components/schemas/Figure'
        - type: object
          properties:
            radius:
              type: number
              example: 19.01
    Triangle:
      allOf:
        - $ref: '#/components/schemas/Figure'
        - type: object
          properties:
            side1:
              type: number
              example: 9.11
            side2:
              type: number
              example: 11.22
            side3:
              type: number
              example: 15.33
    Rectangle:
      allOf:
        - $ref: '#/components/schemas/Figure'
        - type: object
          properties:
            side1:
              type: number
              example: 44.25
            side2:
              type: number
              example: 56.15
    SquareResponse:
      allOf:
        - $ref: '#/components/schemas/Figure'
        - type: object
          properties:
            square:
              type: string
              example: '199.99'